import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import WalletContextProvider from "@/components/WalletProvider";
import "@/styles/wallet.css";


const dm_sans = DM_Sans({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] // Include all available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} antialiased`}>
      <WalletContextProvider>{children}</WalletContextProvider>
      </body>
    </html>
  );
}
